### ISSUE TITLE
training src?

### ISSUE THREAD

**Issue by gembin** [rockyzhengwu/FoolNLTK#1]
COOL！ 没有训练的代码吗？

**Comment by rockyzhengwu** [comment]
谢谢！　训练代码有，还在整理中，也还在调一些模型，后面弄好会开源的

**Comment by Linusp** [comment]
赞！一直希望有一个用了深度学习但又还支持词典的实现。本来是想自己撸一个的～～接受 contribution 么～

**Comment by cloudtrends** [comment]
Training process is part of FoolNLTK tools , without it FoolNLTK user will lose the ability for custom model for their own scenarios . 

Great work!

**Comment by qiaofei32** [comment]
基于字标注法的，不管是CRF还是classification，一律差评

**Comment by FajunChen** [comment]
@qiaofei32 理由是？

**Comment by FajunChen** [comment]
@rockyzhengwu 请问标注预料是公开的吗？从哪得到？

**Comment by rockyzhengwu** [comment]
@qiaofei32 
Thanks !, I will release training process as soon as possible.

**Comment by rockyzhengwu** [comment]
@FajunChen 
这也是我在纠结的，我尽量争取一下，谢谢！

**Comment by GabrielLin** [comment]
I also hope that the source code about training can be released soon. No perfect projects. We can improve it together. Thanks.

**Comment by computerMoMo** [comment]
给作者点个赞，自己也在搞基于深度学习的分词，但是一直没有想到很合适的词典和深度学习的结合方式，很期待看到训练代码～期待作者的模型～

**Comment by xlturing** [comment]
正好需要LSTM+CRF加带权重词典的方式，期待train代码

**Comment by rockyzhengwu** [comment]
@computerMoMo 词典和模型结果的合并方式在这个项目里
首先分别用模型分词，和词典匹配。把二者的结果合并到一个词图里，然后根据权重寻找最大权路径，模型结果的权重为1, 词典中的词可能有歧义，所以会考虑词的长度。(这方案可能有待优化)

**Comment by gembin** [comment]
@rockyzhengwu  有什么进展吗？

**Comment by MRSUNGIT** [comment]
期待训练的代码

**Comment by luobotaxinghu** [comment]
CRF 部分 是使用的 tf.contrib.crf 里面的函数吗?

**Comment by rockyzhengwu** [comment]
我更新了train 的代码

**Comment by FajunChen** [comment]
非常感谢！很好的工作！Excellent!
