### ISSUE TITLE
user dict has no effect in some cases

### ISSUE THREAD

**Issue by sanshe316** [rockyzhengwu/FoolNLTK#13]
user dict in most cases has obvious effect, but not always, e.g.:
contents of user_dict.txt:
二十 10000
四百 10000
一千 10000
When run the command:
echo "一一千四百二十九" | python3 -m fool -d -u user_dict.txt
the result is "一一千四百二十九", not be cut apart. 
But if the sentence to be cut is  "一千四百二十九", it will be cut to "一千 四百 二十 九". That's what I want.
How to explain the results and what can be done if I want the result be:  "一 一千 四百 二十 九"?

**Comment by rockyzhengwu** [comment]
when merge dictionary the algorithm  is not global optimization now .
  when meet first "一"  that isn't in the dictionary will return the result: "一一千四百二十九" 。　
you can add "一" do dict . but there may some new problem ....
thanks you post this ,i try to fix this !

**Comment by rockyzhengwu** [comment]
i fixed this at version 0.0.9.1 .

**Comment by sanshe316** [comment]
Thank you, you are very efficient, but now neither "一一千四百二十九" nor "一千四百二十九" can be cut apart.
