### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by GhibliField** [rockyzhengwu/FoolNLTK#15]
I ran the example in the README to segment a Chinese sentense , but a TypeError occured as follow

	$ python3
	Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
	[GCC 5.4.0 20160609] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import fool
	>>> text="一个傻子在北京"
	>>> print(fool.cut(text))
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/usr/local/lib/python3.5/dist-packages/fool/__init__.py", line 65, in cut
	    all_words = LEXICAL_ANALYSER.cut(text)
	  File "/usr/local/lib/python3.5/dist-packages/fool/lexical.py", line 98, in cut
	    self._load_seg_model()
	  File "/usr/local/lib/python3.5/dist-packages/fool/lexical.py", line 39, in _load_seg_model
	    self.seg_model = self._load_model("seg.pb", "char_map", "seg_map")
	  File "/usr/local/lib/python3.5/dist-packages/fool/lexical.py", line 35, in _load_model
	    char_to_id, id_to_seg = _load_map_file(self.map_file_path, word_map_name, tag_name)
	  File "/usr/local/lib/python3.5/dist-packages/fool/lexical.py", line 18, in _load_map_file
	    data = json.load(myfile)
	  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
	    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
	  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
	    s.__class__.__name__))
	TypeError: the JSON object must be str, not 'bytes'

How to handle this error? Many thanks !

FYI：
- foolnltk version: 0.1.1 ( *installed by* **sudo pip3 install foolnltk --no-cache-dir** )
- python35
- ubuntu16.4(x64)

**Comment by rockyzhengwu** [comment]
Witch version ?

**Comment by rockyzhengwu** [comment]
@GhibliField 
can you post you code ?

**Comment by rockyzhengwu** [comment]
@GhibliField 

```pip install foolnltk --no-cache-dir``` maybe can help you!!!!

**Comment by dong-s** [comment]
@rockyzhengwu 
```
def _load_map_file(path, char_map_name, id_map_name):
    with ZipFile(path) as myzip:
        with myzip.open('all_map.json') as myfile:
            data = json.load(myfile)
            return data.get(char_map_name), data.get(id_map_name)
```
在你这方法中，json.load 无法加载你zip文件中all_map.json

**Comment by rockyzhengwu** [comment]
@dong-s 
报什么错呢？

**Comment by dong-s** [comment]
![deepinscrot-3428](https://user-images.githubusercontent.com/14340719/35132197-ec196c8e-fd04-11e7-9249-32871684b709.png)

我把它解压后直接加载就没问题了
```
def _load_map_file(path, char_map_name, id_map_name):
    with open(path) as myfile:
        data = json.load(myfile)
        return data.get(char_map_name), data.get(id_map_name)
```

**Comment by dong-s** [comment]
@rockyzhengwu

**Comment by rockyzhengwu** [comment]
@dong-s 
是一样的

**Comment by GhibliField** [comment]
Thanks! It works
