### ISSUE TITLE
关于分词和NER结果的结构问题

### ISSUE THREAD

**Issue by wlhgtc** [rockyzhengwu/FoolNLTK#18]
fool.analysis 和fool.cut 的结果之前版本都是返回一个list结构，现在（0.1.3）为什么是一个嵌套的list呢？有什么特殊作用吗？

<img width="570" alt="2018-01-22 9 31 16" src="https://user-images.githubusercontent.com/16603773/35201515-1ddd8f62-ff57-11e7-89e2-3606bf2dc349.png">

**Comment by rockyzhengwu** [comment]
@wlhgtc 
这是为了一次处理多个句子增加的, 可以传一个句子的```list``` 就可以利用tensorflow批量计算

**Comment by rockyzhengwu** [comment]
参考这个[issues
](https://github.com/rockyzhengwu/FoolNLTK/issues/2)
