### ISSUE TITLE
./main.sh map error

### ISSUE THREAD

**Issue by txAnnie** [rockyzhengwu/FoolNLTK#19]
![image](https://user-images.githubusercontent.com/16554293/35207187-95e4a534-ff7c-11e7-9332-2ba82559913a.png)

I got this error when run ./main.sh data. How can I solve this

**Comment by rockyzhengwu** [comment]
@txAnnie 
can you give me more information ?
you can check if train file format is right .
every line in train file split by ```\t```

**Comment by txAnnie** [comment]
Thanks for your reply, I've solved it myself. thanks so much any way.
