### ISSUE TITLE
NER种类有哪些，分别是什么含义

### ISSUE THREAD

**Issue by OptimusV5** [rockyzhengwu/FoolNLTK#2]
试了下感觉准确率蛮高的，点个赞！
但是有个疑问，就是不知道此项目识别出的NER都有哪些，分别有什么具体的含义，比如product这个实体，是指一个真正的产品如一款汽车，还是说包含了所有人类智慧的产物，例如一本书，希望能有明确的定义，谢谢！

**Comment by rockyzhengwu** [comment]
建议使用 ```company```, ```person```, ```time```, ```location``` 其他的会在后面的版本中去掉

**Comment by OptimusV5** [comment]
明白了，谢谢！
