### ISSUE TITLE
./mian export

### ISSUE THREAD

**Issue by txAnnie** [rockyzhengwu/FoolNLTK#22]
![image](https://user-images.githubusercontent.com/16554293/35472762-4e1eaffa-03b0-11e8-9974-c299594bc28c.png)

I've got this error when run './main export', how can I fixed it?

**Comment by rockyzhengwu** [comment]
sorry , I have no idea.
I run this on CPU
good lucky to you !

**Comment by txAnnie** [comment]
Ok, thank you.
