### ISSUE TITLE
模型文件

### ISSUE THREAD

**Issue by 18222278799** [rockyzhengwu/FoolNLTK#24]
您好，我想问一下， 如果我暂时不训练模型，您的文件里有训练好的模型么，我想直接利用模型进行分词测试。

**Comment by rockyzhengwu** [comment]
```
pip install foolnltk
```

```
import fool

text = "一个傻子在北京"
print(fool.cut(text))
# ['一个', '傻子', '在', '北京']
```

**Comment by 18222278799** [comment]
谢谢，了解了，🙏




| |
张天霖
邮箱：18222278799@163.com
|

签名由 网易邮箱大师 定制

在2018年03月07日 15:13，wu.zheng 写道：
pip install foolnltk

import fool

text = "一个傻子在北京"
print(fool.cut(text))
# ['一个', '傻子', '在', '北京']
