### ISSUE TITLE
支持python2.7

### ISSUE THREAD

**Issue by leepand** [rockyzhengwu/FoolNLTK#25]
仅需将fool目录下model.py中的
def load_map(path):
    with open(path, 'rb') as f:
        char_to_id,  tag_to_id, id_to_tag = pickle.load(f)
    return char_to_id, id_to_tag
改为：
def load_map(path):
    with open(path) as f:
        char_to_id,  tag_to_id, id_to_tag = pickle.load(f)
    return char_to_id, id_to_tag
即可

**Comment by rockyzhengwu** [comment]
谢谢，已修改，发了个新的版本0.1.5
