### ISSUE TITLE
Please upload map.zip 

### ISSUE THREAD

**Issue by devshilei** [rockyzhengwu/FoolNLTK#27]
工程执行中有爆出如下错误：
`FileNotFoundError: [Errno 2] No such file or directory: `'/usr/fool/map.zip'`
查看代码，另外还有可能需要load这些文件：
def _load_seg_model(self):
        self.seg_model = self._load_model("seg.pb", "char_map", "seg_map")

    def _load_pos_model(self):
        self.pos_model = self._load_model("pos.pb", "word_map", "pos_map")

    def _load_ner_model(self):
        self.ner_model = self._load_model("ner.pb", "char_map", "ner_map")

劳烦作者提供相关下载包，不胜感激。

**Comment by rockyzhengwu** [comment]
这个文件就在项目的data下，我默认是放在```sys.prefix```下的，如果不能加载，你需要把模型文件copy 到你的环境的```sys.prefix```下，在python 下打印```sys.prefix```就能看到这个路径是什么。
