### ISSUE TITLE
怎么训练实体识别的模型（how to train ner model）

### ISSUE THREAD

**Issue by zhishan332** [rockyzhengwu/FoolNLTK#28]
怎么自己训练实体识别模型？根据文档成功了训练了自己的分词模型，实体识别的训练过程有介绍吗

**Comment by rockyzhengwu** [comment]
实体模型，我没做特别的改动，跟分词是一样的，基于字的。如果你要增加其他特征就要修改代码了

**Comment by zhishan332** [comment]
明白了谢谢

**Comment by fooSynaptic** [comment]
训练出来模型的实际的效果就是和pypi上面的一样吗
那是不是CRF都没有用上？

**Comment by fooSynaptic** [comment]
没有仔细看代码，原来分词训练就是用crf，我还以为是分类

**Comment by zhangjiantong** [comment]
请问实体识别模型是基于bert训练吗，还是lstm?
