### ISSUE TITLE
What is the license of FoolNLTK source code , model and corpus ?

### ISSUE THREAD

**Issue by cloudtrends** [rockyzhengwu/FoolNLTK#3]
hi all ,

I want to integrate FoolNLTK into my project for personal use or may be in business product .
 
So , what is the license of FoolNLTK source code , model and corpus ?

Can we separate the source code , model and corpus with different license ?

Thanks in advance .

**Comment by rockyzhengwu** [comment]
I think there is no problem.
you can read this [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/)
OR the [LICENCE](https://github.com/rockyzhengwu/FoolNLTK/blob/master/LICENSE) file in the project.

enjoy yourself!
