### ISSUE TITLE
研究了您的源代码，发现/fool/lexical.py文件中LexicalAnalyzer中ner方法中，返回的索引值的右侧值似乎是多加了1

### ISSUE THREAD

**Issue by Zoe233** [rockyzhengwu/FoolNLTK#32]
如题。
跑test中ner方法调用，得到的结果是
ners: [[(2, 8, 'location', '北京天安门')], [(2, 5, 'location', '北京'), (9, 12, 'location', '非洲')], [], [(2, 8, 'location', '北京天安门')]]
==>但是实际上'北京天安门'等实体的在text中的文本索引应该是(2,7)才对。
后面还尚未研究是否有别的用意？
仅以记录单词在句子中的索引值的概念来理解的话，此处似乎是多加了1.

**Comment by rockyzhengwu** [comment]
我应该是希望能和Python list 里面的切片的逻辑一致即:包含下界，不包含上届这样就直接用到```text[start:end]```
