### ISSUE TITLE
载入自己训练的模型时发生错误

### ISSUE THREAD

**Issue by betachat** [rockyzhengwu/FoolNLTK#34]
我的环境：
ubuntu 18.04 

错误代码如下
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 1: invalid start byte`

**Comment by billyyong** [comment]
编译word2vec
cd third_paty && make

在这里我就出错了

**Comment by betachat** [comment]
@billyyong 原本的好像就編譯過了
而且原作者拼錯了的樣子 是party

**Comment by billyyong** [comment]
这里的训练，是分词训练，不是ner的训练吧

**Comment by mountainguan** [comment]
@billyyong 我想增加一个需要被识别的实体类型，好像这个项目不支持？

**Comment by betachat** [comment]
在已經closed的issue中說明過了
都是基於字的標記，你稍微看看代碼應該就行了。

**Comment by rockyzhengwu** [comment]
@mountainguan 包含训练代码的，你看下训练的文档
@billyyong word2vec你可以重新编译
@betachat 编码问题有解决吗

**Comment by billyyong** [comment]
您之前的ner训练语料有吗，不知道您用的格式，还有增加一个实体类别，需要改程序吗

**Comment by billyyong** [comment]
@rockyzhengwu 您之前的ner训练语料有吗，不知道您用的格式，还有增加一个实体类别，需要改程序吗

**Comment by rockyzhengwu** [comment]
@billyyong 格式和分词是一样的，如果你有有语料，你可以重新训练自己的模型，

**Comment by betachat** [comment]
謝謝
