### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/fool/map.zip'

### ISSUE THREAD

**Issue by c0derm4n** [rockyzhengwu/FoolNLTK#38]
pip3 install foolnltk后
执行示例代码
出现filenotfound

**Comment by rockyzhengwu** [comment]
你看下 sys.prefix 的路径，把文件copy到这个路径下就好，文件是在你机器上的应该，但路径不一致

**Comment by yuhc0721** [comment]
我的sys.prefix路径是/usr，但是fool文件夹copy不进去。有什么修改sys.prefix路径的方法吗？
