### ISSUE TITLE
訓練失敗

### ISSUE THREAD

**Issue by ray1422** [rockyzhengwu/FoolNLTK#39]
您好
在我使用自己的语料训练模型时出现以下错误
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [6299,100] rhs shape= [1104,100]
(在步骤 train时，前面tfrecord都通过了)

请问该如何解决..

**Comment by betachat** [comment]
把result資料夾清空試試

**Comment by ray1422** [comment]
謝謝!!
