### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by adzhua** [rockyzhengwu/FoolNLTK#4]
你好，我在测试的时候有时会报：
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x0000000019C8A208>>
再次运行的时候又正常，我使用的平台为tensorflow 1.4.0 win7。这是我的版本问题吗？

**Comment by wodeweilai** [comment]
ReadMe上写了只在Linux上测试通过，可能是Win还不支持

**Comment by rockyzhengwu** [comment]
@adzhua 装的是什么版本的foolnltk 和tensorflow?

**Comment by adzhua** [comment]
foolnltk 是0.0.8；tensorflow是1.4.0

在 2017-12-28 13:03:25，"wu.zheng" <notifications@github.com> 写道：


@adzhua 装的是什么版本的foolnltk 和tensorflow?

**Comment by adzhua** [comment]
@wodeweilai foolnltk 是0.0.8；tensorflow是1.4.0，确定传的是非空的字符串

**Comment by adzhua** [comment]
@rockyzhengwu foolnltk 是0.0.8；tensorflow是1.4.0；确认传的是非空的字符串，传入同样的字符串，出现错误后再次运行又正常。

**Comment by rockyzhengwu** [comment]
我在Ubuntu上测过tensorflow 1.4.0, 也没有你说的错误，你能定位具体报错的是哪行代码吗？

**Comment by adzhua** [comment]
@rockyzhengwu 难道是系统的原因？刚运行报如下错误：
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x0000000019C7A080>>
Traceback (most recent call last):
  File "D:\python3.5\lib\site-packages\tensorflow\python\client\session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable
我调用words, ners = fool.analysis(text)结果是可以出来。

**Comment by gdh756462786** [comment]
你好！出现  ValueError: could not convert string to float: '据时，如果忽略上下文和单词顺序的信息，那么我们将会丢掉许多重要的信息。'怎么解决？

**Comment by rockyzhengwu** [comment]
@gdh756462786 能给个例子吗？没明白你什么意思

**Comment by iiapache** [comment]
请问支持tensorflow 1.0.1吗？

**Comment by rockyzhengwu** [comment]
@iiapache 没测过，你可以测一下
