### ISSUE TITLE
大佬您好。请问下，关于词性标注和实体识别，foolnltk所采用的语料情况是咋样的？能够复用你的模型训练过程，进行实体识别模型的训练吗？

### ISSUE THREAD

**Issue by george-sq** [rockyzhengwu/FoolNLTK#40]
大佬您好。请问下，关于词性标注和实体识别，foolnltk所采用的语料情况是咋样的？能够复用你的模型训练过程，进行实体识别模型的训练吗？

**Comment by fooSynaptic** [comment]
在文档中提供的训练过程貌似是分词的训练，而关于词性标注和实体识别的训练部分在文档中没有提供。
`>>> import fool
/Users/hujiaxin/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> map_file = "./datasets/demo/maps.pkl"
>>> checkpoint_ifle = "./results/demo_seg/modle.pb"
>>> smodel = fool.load_model(map_file=map_file, model_file=checkpoint_ifle)
2018-08-01 15:28:46.517215: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
>>> tags = smodel.predict(["北京欢迎你", "你在哪里"])
>>> tags
[['B', 'S', 'S', 'S', 'E'], ['S', 'S', 'S', 'E']]`

**Comment by ray1422** [comment]
都是基於字的，另外人名識別的準確度，男生明顯低於女生名（滑稽
