### ISSUE TITLE
您好，我仔细看过源码发现您训练的任务是一个标注label的任务，那么在fool模块中提供的词性标注和主题识别是怎么做到的呢？

### ISSUE THREAD

**Issue by fooSynaptic** [rockyzhengwu/FoolNLTK#41]
这个label是B-词首，M-词中，E-词尾和S-单独成词，所以最后的模型也只能做分词的任务，那么模块中的其他功能是如何实现的？

**Comment by ray1422** [comment]
實體識別是基於字的，我想原始的詞性識別應該也是
你可以簡單閱讀代碼，然後把它印出來就行了
