### ISSUE TITLE
能解释下crf那段代码。为什么要pad_logits，并且num_tags + 1吗？

### ISSUE THREAD

**Issue by Aifcce** [rockyzhengwu/FoolNLTK#47]
在训练代码中。bi_lstm文件的 loss_layer中，在计算crf之前。为什么要对。logits和target做一个填充。增加纬度

**Comment by shillyshallysxy** [comment]
有同样的困惑，请问您知道该问题的答案了吗？

**Comment by Aifcce** [comment]
> 有同样的困惑，请问您知道该问题的答案了吗？

我暂时还不知道原因，我自己试验的时候没有做最后的pad，也有不错的结果。我感觉他的这种做法有点标记句子开头句子结尾的意思。

**Comment by shillyshallysxy** [comment]
好的，谢谢！我先按自己的想法实现试试

**Comment by rockyzhengwu** [comment]
@shillyshallysxy 就是标记句子开头，当时也是看原作者的代码记得有加句子开头和结尾，我只加了开头
