### ISSUE TITLE
analysis进行实体识别并对于自定义加载的字典无效。

### ISSUE THREAD

**Issue by fyh97** [rockyzhengwu/FoolNLTK#52]
博主，您好。最近在用您的代码进行中文分词时，在加载了自定义词典后，分词部分能被准确分出，但当进行实体识别时发现这个过程并没有加载自定义词典。。
以及想问博主加载的字典之后能否支持自定义的词性。

**Comment by rockyzhengwu** [comment]
实体识别的模型是和词典无关的，实体识别的模型和分词没关系，你可以自己把词典的实体加进去就好了
