### ISSUE TITLE
安装不了foolnltk

### ISSUE THREAD

**Issue by ckbckb** [rockyzhengwu/FoolNLTK#53]
出现ERROR: Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
安装不了，求救

**Comment by rockyzhengwu** [comment]
遇到 bug 应该是仔细分析问题，既然提了 issues 要说清楚问题相关的背景，你现在是安装问题，那得说清楚你是操作系统，什么 Python 版本， 怎么装的， 错误日志如何。 而不是大呼小叫。
