### ISSUE TITLE
布置在服务器上，处理数据时，时快时慢是怎么回事？

### ISSUE THREAD

**Issue by douweigang** [rockyzhengwu/FoolNLTK#54]
布置在服务器上，处理数据时，时快时慢是怎么回事？有时1秒，有时一二十秒

**Comment by KevinChen1994** [comment]
请问问题解决了吗？我这边在用NER的时候，第一次请求就会特别慢，后边会很快。

**Comment by douweigang** [comment]
第一次慢，是因为需要加载模型，，后面快了不就好了吗？后来我用别的方式部署了，也还行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈猛"<notifications@github.com&gt;; 
发送时间: 2020年3月2日(星期一) 中午1:23
收件人: "rockyzhengwu/FoolNLTK"<FoolNLTK@noreply.github.com&gt;; 
抄送: "窦伟刚"<513856032@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rockyzhengwu/FoolNLTK] 布置在服务器上，处理数据时，时快时慢是怎么回事？ (#54)




请问问题解决了吗？我这边在用NER的时候，第一次请求就会特别慢，后边会很快。
