### ISSUE TITLE
ImportError!

### ISSUE THREAD

**Issue by Freakwill** [rockyzhengwu/FoolNLTK#57]
ImportError: cannot import name 'dense_features' from 'tensorflow.python.feature_column' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/feature_column/__init__.py)

**Comment by rockyzhengwu** [comment]
tensorflow version <=1.14

**Comment by zhengcong1** [comment]
So, how to solve this problem? I also met this.
